### ISSUE TITLE
htsdb-count-reads crashes if no entries are found

### ISSUE THREAD

**Issue by palexiou** [mnsmar/htsdb#1]
If the filter excludes all entries of the database the count reads script crashes instead of just returning 0 counts.

![image](https://cloud.githubusercontent.com/assets/1820368/18998687/b8aba2d2-8707-11e6-8be8-3cf1bb2938de.png)

**Comment by mnsmar** [comment]
Fixed in 7bd507cdcf011213db15e54f7af1ce41fdfb5047.
